kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitcoin-daemon-pv-claim
spec:
  storageClassName: {{ .Values.bitcoin.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bitcoin.storage.size }}