bitcoin:
  image:
    name: "sajithagimash/bitcoin-daemon"
    tag: "1.0.0"
    pullPolicy: Always
    volume:
      mountPath: "/mnt/data/bitcoin"
  storage:
    className: "managed-nfs-storage"
    size: "800Gi"
  nodeSelector:
    key: "kubernetes.io/hostname"
    value: "cybubcibrdev001"
  service:
    port: 8332
    targetPort: 8332
