bitcoin:
  image:
    name: "sajithagimash/bitcoin-parser"
    tag: "1.0.0"
    pullPolicy: Always
    volume:
      mountPath: "/mnt/data/bitcoin"
  storage:
    className: "managed-nfs-storage"
    size: "800Gi"
  nodeSelector:
    key: "kubernetes.io/hostname"
    value: "cybubcibrdev001"
  service:
    port: 8332
    targetPort: 8332
  parser:
    startBlockHeight: "0"
    endBlockHeight: "100000"
    batchSize: "100000"
  # rabbitmq:
  #   token: rabbitmq-token-sqlzz
  #   password: rabbitmq
