kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: toshi-airflow-pvc
  namespace: airflow-cluster
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Gi"
