---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greenplum-system-operator
rules:
- apiGroups: [greenplum.pivotal.io]
  resources: [greenplumclusters]
  verbs: ['*']
- apiGroups: [greenplum.pivotal.io]
  resources: [greenplumplservices]
  verbs: ['*']
- apiGroups: [greenplum.pivotal.io]
  resources: [greenplumpxfservices]
  verbs: ['*']
- apiGroups: [greenplum.pivotal.io]
  resources: [greenplumtextservices]
  verbs: ['*']
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [get]
- apiGroups: [certificates.k8s.io]
  resources: [certificatesigningrequests]
  verbs: [create, delete, list, watch]
- apiGroups: [certificates.k8s.io]
  resources: [certificatesigningrequests/approval]
  verbs: [update]
- apiGroups: [certificates.k8s.io]
  resources: [signers]
  resourceNames: [kubernetes.io/legacy-unknown]
  verbs: [approve]
- apiGroups: [admissionregistration.k8s.io]
  resources: [validatingwebhookconfigurations]
  verbs: [create, get, update]
- apiGroups: [apps]
  resources: [deployments]
  verbs: ['*']
- apiGroups: [apps]
  resources: [statefulsets]
  verbs: ['*']
- apiGroups: [batch]
  resources: [jobs]
  verbs: ['*']
- apiGroups: [""]
  resources: [configmaps]
  verbs: ['*']
- apiGroups: [""]
  resources: [secrets]
  verbs: ['*']
- apiGroups: [""]
  resources: [pods]
  verbs: ['*']
- apiGroups: [""]
  resources: [nodes]
  verbs: ['*']
- apiGroups: [""]
  resources: [services]
  verbs: ['*']
- apiGroups: [""]
  resources: [endpoints]
  verbs: ['*']
- apiGroups: [""]
  resources: [persistentvolumeclaims]
  verbs: ['*']
- apiGroups: [""]
  resources: [events]
  verbs: ['*']
- apiGroups: [""]
  resources: [namespaces]
  verbs: [list, watch]
- apiGroups: [""]
  resources: [pods/exec]
  verbs: [create]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: [create, list, update, watch]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: [roles]
  verbs: [create, list, update, watch]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: [rolebindings]
  verbs: [create, list, update, watch]
